Repository si-2019/mike-kolaboracija, pull requests merged in 2019-06, with the labels that each got.

#29 Sprint #6 - Student ima mogucnost da postavlja fajlove unutar zadataka
  backend-kb/api/students/workAPI.js
  backend-kb/models/ProjektniFile.js
  backend-kb/models/db.js
  backend-kb/package-lock.json
  backend-kb/package.json
  backend-kb/routes/students/workRoute.js
  backend-kb/temp_files/tempfile
  backend-kb/utils/studentUtils/workUtils.js
Labels: Ready4Review

#30 Sprint #8 - Student vodja ima mogucnost brisanja svih fajlova u projektu
  backend-kb/api/students/workAPI.js
  backend-kb/routes/students/workRoute.js
  backend-kb/tests/students/deleteFilesTests.js
  backend-kb/utils/studentUtils/workUtils.js
Labels: Pushed

#31 Nove funkcionalnosti i sprintovi 01.06.2019
  backend-kb/README.md
  backend-kb/SwaggerAPI.yml
  backend-kb/SwaggerService.yml
  backend-kb/api/asistants/bodovanjeAPI.js
  backend-kb/api/students/viewSAPI.js
  backend-kb/api/students/workAPI.js
  backend-kb/index.js
  backend-kb/models/ProjektniFile.js
  backend-kb/models/db.js
  backend-kb/models/projektniZadatak_clanGrupe.js
  backend-kb/package-lock.json
  backend-kb/package.json
  backend-kb/routes/asistants/bodovanjeRoute.js
  backend-kb/routes/asistants/projectsRoute.js
  backend-kb/routes/outsourced/servisiRoute.js
  backend-kb/routes/students/viewSRoute.js
  backend-kb/routes/students/workRoute.js
  backend-kb/temp_files/tempfile
  backend-kb/tests/asistants/bodovanjeProjektaPojedinacnoTests.js
  backend-kb/tests/asistants/skaliranjeBodovaTests.js
  backend-kb/tests/asistants/tasksTests.js
  backend-kb/tests/students/assignTaskTests.js
  backend-kb/tests/students/deleteFilesTests.js
  backend-kb/tests/students/selectLeaderTests.js
  backend-kb/utils/asistantUtils/bodovanjeUtils.js
  backend-kb/utils/asistantUtils/generateUtils.js
  backend-kb/utils/asistantUtils/projectsUtils.js
  backend-kb/utils/studentUtils/groupUtils.js
  backend-kb/utils/studentUtils/viewSUtils.js
  backend-kb/utils/studentUtils/workUtils.js
Labels: SprintDone, enhancement

#32 Kreiranje servisa za dohvatanje detalja projekta
  backend-kb/package-lock.json
  backend-kb/routes/asistants/viewARoute.js
  backend-kb/routes/outsourced/servisiRoute.js
  backend-kb/utils/asistantUtils/viewAUtils.js
Labels: Ready4Review

#33 update master minor
  backend-kb/package-lock.json
  backend-kb/routes/asistants/viewARoute.js
  backend-kb/routes/outsourced/servisiRoute.js
  backend-kb/utils/asistantUtils/viewAUtils.js
Labels: enhancement

#37 final develop -> master
  backend-kb/routes/students/progressRoute.js
  backend-kb/utils/asistantUtils/projectsUtils.js
  backend-kb/utils/asistantUtils/viewAUtils.js
  backend-kb/utils/studentUtils/progressUtil.js
Labels: enhancement
