Repository si-2019/mike-kolaboracija, pull requests merged in 2019-05, with the labels that each got.

#8 Sprint #3 - Student ima mogucnost dodavanja drugih clanova grupe
  backend-kb/routes/asistants/projectsRoute.js
  backend-kb/routes/students/groupRoute.js
  backend-kb/routes/students/workRoute.js
  backend-kb/tests/students/addmembersTests.js
  backend-kb/tests/students/groupTests.js
  backend-kb/utils/asistantUtils/projectsUtils.js
  backend-kb/utils/studentUtils/groupUtils.js
Labels: Ready4Review

#11 Mike asistent ima mogucnost da boduje projekte
  backend-kb/models/ClanGrupe.js
  backend-kb/package-lock.json
  backend-kb/package.json
  backend-kb/routes/asistants/projectsRoute.js
  backend-kb/tests/asistants/bodovanjeProjektaTests.js
  backend-kb/utils/asistantUtils/projectsUtils.js
  backend-kb/utils/studentUtils/groupUtils.js
  backend-kb/utils/studentUtils/workUtils.js
Labels: Ready4Review

#10 Sprint #2 - ispravak testova
  backend-kb/package-lock.json
  backend-kb/tests/students/groupTests.js
Labels: Ready4Review

#12 Završen backend dio za sprint #3 i ispravljeni testovi za sprint #2
  backend-kb/index.js
  backend-kb/models/ClanGrupe.js
  backend-kb/package-lock.json
  backend-kb/routes/asistants/bodovanjeRoute.js
  backend-kb/routes/asistants/generateRoute.js
  backend-kb/routes/asistants/projectsRoute.js
  backend-kb/routes/asistants/viewARoute.js
  backend-kb/routes/students/groupRoute.js
  backend-kb/routes/students/progressRoute.js
  backend-kb/routes/students/viewSRoute.js
  backend-kb/routes/students/workRoute.js
  backend-kb/tests/asistants/bodovanjeProjektaTests.js
  backend-kb/tests/asistants/newpTests.js
  backend-kb/tests/students/addmembersTests.js
  backend-kb/tests/students/groupTests.js
  backend-kb/utils/asistantUtils/bodovanjeUtils.js
  backend-kb/utils/asistantUtils/generateUtils.js
  backend-kb/utils/asistantUtils/projectsUtils.js
  backend-kb/utils/asistantUtils/viewAUtils.js
  backend-kb/utils/studentUtils/groupUtils.js
  backend-kb/utils/studentUtils/progressUtil.js
  backend-kb/utils/studentUtils/viewSUtils.js
  backend-kb/utils/studentUtils/workUtils.js
Labels: SprintDone

#13 Sprint #4 - Asistent ima mogucnost da boduje projekte u cijelosti na nacin da pojedinacno dodijeli bodove studentima
  backend-kb/package-lock.json
  backend-kb/routes/asistants/bodovanjeRoute.js
  backend-kb/tests/asistants/bodovanjeProjektaPojedinacnoTests.js
  backend-kb/tests/asistants/bodovanjeProjektaTests.js
  backend-kb/tests/asistants/newpTests.js
  backend-kb/utils/asistantUtils/bodovanjeUtils.js
Labels: Ready2Push

#16 #Swagger - update API i SERVISA
  backend-kb/api/asistants/bodovanjeAPI.js
  backend-kb/api/asistants/generateAPI.js
  backend-kb/api/asistants/projectsAPI.js
  backend-kb/api/asistants/viewAAPI.js
  backend-kb/api/students/groupAPI.js
  backend-kb/api/students/progressAPI.js
  backend-kb/api/students/viewSAPI.js
  backend-kb/api/students/workAPI.js
  backend-kb/index.js
  backend-kb/routes/asistants/bodovanjeRoute.js
  backend-kb/routes/asistants/projectsRoute.js
  backend-kb/routes/students/groupRoute.js
  backend-kb/routes/students/workRoute.js
  backend-kb/swaggerDoc.js
  backend-kb/tests/asistants/bodovanjeProjektaPojedinacnoTests.js
  backend-kb/tests/asistants/bodovanjeProjektaTests.js
  backend-kb/tests/asistants/dodavanjeRokaTests.js
  backend-kb/tests/asistants/newpTests.js
  backend-kb/tests/students/addmembersTests.js
  backend-kb/tests/students/groupTests.js
  backend-kb/tests/students/selectLeaderTests.js
  backend-kb/tests/students/workTests.js
  backend-kb/utils/studentUtils/groupUtils.js
Labels: enhancement

#18 Mike asistent ima mogucnost da generise projektne grupe abecedno
  backend-kb/api/asistants/generateAPI.js
  backend-kb/models/AkademskaGodina.js
  backend-kb/models/db.js
  backend-kb/models/predmet_student.js
  backend-kb/package-lock.json
  backend-kb/package.json
  backend-kb/routes/asistants/generateRoute.js
  backend-kb/tests/asistants/generisanjeGrupaAbecednoTests.js
  backend-kb/utils/asistantUtils/generateUtils.js
Labels: Ready4Review

#19 Student ima mogucnost prikaza grafickog interfejsa za uredjivanje clanova grupe
  backend-kb/routes/students/groupRoute.js
  backend-kb/utils/studentUtils/groupUtils.js
Labels: Pushed

#21 Završen backend dio sprinta #5
  backend-kb/routes/students/viewSRoute.js
  backend-kb/utils/asistantUtils/generateUtils.js
  backend-kb/utils/studentUtils/viewSUtils.js
Labels: SprintDone

#23 Sprint #6 - Asistent ima mogucnost da boduje pojedinacne projektne zadatke
  backend-kb/README.md
  backend-kb/api/asistants/bodovanjeAPI.js
  backend-kb/models/projektniZadatak_clanGrupe.js
  backend-kb/routes/asistants/bodovanjeRoute.js
  backend-kb/tests/asistants/bodovanjeProjektaPojedinacnoTests.js
  backend-kb/tests/asistants/tasksTests.js
  backend-kb/tests/students/selectLeaderTests.js
  backend-kb/utils/asistantUtils/bodovanjeUtils.js
  backend-kb/utils/studentUtils/groupUtils.js
Labels: Ready2Push

#26 Sprint #9 - Asistent ima mogucnost skaliranja bodova na projektu
  backend-kb/api/asistants/bodovanjeAPI.js
  backend-kb/routes/asistants/bodovanjeRoute.js
  backend-kb/tests/asistants/skaliranjeBodovaTests.js
  backend-kb/utils/asistantUtils/bodovanjeUtils.js
  backend-kb/utils/asistantUtils/generateUtils.js
Labels: Pushed
