Repository si-2019/mike-kolaboracija, pull requests merged in 2019-04, with the labels that each got.

#1 Sprint #1 - Kao-student/potrebno-je-da-imam-mogucnost-kreiranja-projektnih-zadataka-kako-bi-ih-dodao-u-projekat
  backend-kb/routes/students/workRoute.js
  backend-kb/tests/students/workAcceptanceTests.js
Labels: Ready2Push

#3 Sprint #2 - Asistent ima mogucnost kreiranja projekta na nivou predmeta
  backend-kb/README.md
  backend-kb/index.js
  backend-kb/package.json
  backend-kb/routes/asistants/izbrisati.txt
  backend-kb/routes/asistants/projectsRoute.js
  backend-kb/routes/students/workRoute.js
  backend-kb/tests/asistants/izbrisati.txt
  backend-kb/tests/asistants/projectsTests.js
  backend-kb/tests/students/workTests.js
  backend-kb/utils/asistantUtils/izbrisati.txt
  backend-kb/utils/asistantUtils/projectsUtils.js
Labels: Ready2Push

#4 Mike asistent ima mogucnost postavljanja roka za izradu projekta kako bi ogranicio vrijeme izrade
  backend-kb/package-lock.json
  backend-kb/package.json
  backend-kb/routes/asistants/projectsRoute.js
  backend-kb/tests/asistants/dodavanjeRokaTests.js
  backend-kb/utils/asistantUtils/projectsUtils.js
Labels: Pushed

#7 Završen backend dio za sprint #2
  README.md
  backend-kb/.env
  backend-kb/README.md
  backend-kb/db.js
  backend-kb/index.js
  backend-kb/models/ClanGrupe.js
  backend-kb/models/GrupaProjekta.js
  backend-kb/models/Korisnik.js
  backend-kb/models/Predmet.js
  backend-kb/models/Projekat.js
  backend-kb/models/ProjektniFile.js
  backend-kb/models/ProjektniZadatak.js
  backend-kb/models/db.js
  backend-kb/models/projektniZadatak_clanGrupe.js
  backend-kb/package-lock.json
  backend-kb/package.json
  backend-kb/routes/asistants/izbrisati.txt
  backend-kb/routes/asistants/projectsRoute.js
  backend-kb/routes/students/groupRoute.js
  backend-kb/routes/students/workRoute.js
  backend-kb/tests/asistants/dodavanjeRokaTests.js
  backend-kb/tests/asistants/izbrisati.txt
  backend-kb/tests/asistants/projectsTests.js
  backend-kb/tests/students/groupTests.js
  backend-kb/tests/students/workAcceptanceTests.js
  backend-kb/tests/students/workTests.js
  backend-kb/utils/asistantUtils/izbrisati.txt
  backend-kb/utils/asistantUtils/projectsUtils.js
  backend-kb/utils/studentUtils/groupUtils.js
  backend-kb/utils/studentUtils/workUtils.js
Labels: SprintDone
